### ISSUE TITLE
.babelrc config version

### ISSUE THREAD

**Issue by pbreah** [Ognian/react-intl-webpack-plugin#4]
using .babelrc file like this:
```javascript
{
  "presets": ["es2015", "react", "stage-2"],
  "metadataSubscribers": "metadataReactIntlPlugin",
  "plugins" : [
    [
      "react-intl", {
        "messagesDir": "./public/build/messages",
        "enforceDescriptions": false
      }
    ]
  ]
}
```

gives this error:

Unknown option: /.babelrc.metadataSubscribers.

I'm using:

    "babel-core": "^6.24.0",
    "babel-loader": "^6.4.1",
    "babel-plugin-react-intl": "^2.3.1",
    "babel-preset-env": "^1.1.4",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-2": "^6.22.0",

I also added:

new ReactIntlPlugin() to the plugins array on the webpack.config.js any ideas?

**Comment by Ognian** [comment]
You can't use a .babelrc file. You must use a  webpack config file. Only that way you can pass the metadatasubscriber function of the webpack plugin to the babel loader ...
